// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBESRIXqh4xmTQCGdvepwssrjj_Avxot_c',
    appId: '1:240948650423:web:ba6f754892a8375d2ec832',
    messagingSenderId: '240948650423',
    projectId: 'tugas2-7a6a9',
    authDomain: 'tugas2-7a6a9.firebaseapp.com',
    storageBucket: 'tugas2-7a6a9.appspot.com',
    measurementId: 'G-3719GQZTN3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0_ZAX1UarQewfQC6oIsSbPZqlmwXe4I',
    appId: '1:240948650423:ios:c31a9945201d7d7a2ec832',
    messagingSenderId: '240948650423',
    projectId: 'tugas2-7a6a9',
    storageBucket: 'tugas2-7a6a9.appspot.com',
    iosBundleId: 'com.example.tugas2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO0_ZAX1UarQewfQC6oIsSbPZqlmwXe4I',
    appId: '1:240948650423:ios:c31a9945201d7d7a2ec832',
    messagingSenderId: '240948650423',
    projectId: 'tugas2-7a6a9',
    storageBucket: 'tugas2-7a6a9.appspot.com',
    iosBundleId: 'com.example.tugas2',
  );
}
